services:
    configurator:
        image: public.ecr.aws/supportpal/helpdesk-configurator:${CONFIGURATOR_VERSION}
        environment:
            SECRETS_DIR: ${SECRETS_DIR}
            HOST_UID: ${HOST_UID:-0}
            HOST_GID: ${HOST_GID:-0}
        volumes:
            - ${SECRETS_DIR}:/secrets/
        network_mode: "bridge"
        command: 'sh /app/scripts/create_secrets.sh'
