name: docker-compose install

on:
  pull_request:
    paths:
      - templates/docker-compose/**/*
      - configs/**/*

defaults:
  run:
    working-directory: ./templates/docker-compose

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 4

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Shellcheck
        run: |
          docker run --rm \
            -v "${PWD}:/v"  \
            -w "/v" \
            koalaman/shellcheck \
            -e SC1091 -e SC1117 \
            *.sh

      - name: docker compose config test
        run: |
          cp ../../configs/templates/.env.custom .env.custom
          docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.https.yml config

      - name: docker compose up
        run: |
          sudo apt install -y expect
          cp ../../configs/templates/.env.custom .env.custom
          cp ../../configs/templates/Makefile Makefile
          expect verify-install.exp

          sleep 5 
          curl -fSL -o /tmp/test.txt http://localhost/
          if ! grep -q "SupportPal" /tmp/test.txt; then
            echo "ERROR: SupportPal is not loading via HTTP"
            exit 3
          fi
        env:
          SUPPORTPAL_LICENSE_KEY: "${{ secrets.SUPPORTPAL_LICENSE_KEY }}"
